sudo: required
services:
  - docker

before_install:
  - docker build -t dmendoza234/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dmendoza234/react-test npm test -- --coverage

after_success:
  - docker build -t dmendoza234/multi-client ./client
  - docker build -t dmendoza234/multi-nginx ./nginx
  - docker build -t dmendoza234/multi-server ./server
  - docker build -t dmendoza234/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push dmendoza234/multi-client
  - docker push dmendoza234/multi-nginx
  - docker push dmendoza234/multi-server
  - docker push dmendoza234/multi-worker

